version: 0.1
phases:
  install:
    commands:
      - npm install chunk
      - aws cloudformation package --template-file template.yaml --s3-bucket VpcSubnetIpMonitor
                                   --output-template-file NewTemplate.yaml
artifacts:
  type: zip
  files:
    - NewTemplate.yaml