AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  VpcSubnetIpMonitor:
    Type: 'AWS::Serverless::Function'
    DependsOn:
      - VpcSubnetIpMonitorRole
    Properties:
      Handler: VpcSubnetIpMonitor/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Events:
        CheckSubnetsScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
  VpcSubnetIpMonitorExecutionPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: VpcSubneIpMonitorExecutionPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'cloudwatch:PutMetricData'
              - 'ec2:DescribeSubnets'
            Resource: '*'
      Roles:
        - Ref: "VpcSubnetIpMonitorRole"
  VpcSubnetIpMonitorRole:
    Type: 'AWS::IAM::Role'
    DependsOn:
      - VpcSubnetIpMonitorExecutionPolicy
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: VpcSubnetIpMonitorRole
